### ISSUE TITLE
sort_keys

### ISSUE THREAD

**Issue by eamtalu** [shahedex/sslcommerz-payment-gateway-python#2]
Hi
While checking your code, I have got one finding.

 @staticmethod
    def sort_keys(data_dict):
        return [(key, data_dict[k])] for key in sorted(data_dict.keys())]

Should it not be: (key, data_dict[key]) ? 

thanks

**Comment by eamtalu** [comment]
Hi,
I have re-written the method after fixing the syntax and dictionary key value. Please check and if you think this is correct.

@staticmethod
    def sort_keys(data_dict):
        return [ (key, data_dict[key]) for key in sorted(data_dict.keys()) ]


Br
Amin

**Comment by shahedex** [comment]
Good catch @eamtalu . Thanks a lot! 
Can you commit your changes and open a Pull Request regarding the fix?
That'd be a great help.

**Comment by eamtalu** [comment]
Thank you very much, indeed I found your code very helpful.
I have become a big fan of your coding style, it is so clean and
understandable.

I am learning python newly.

BR

**Comment by shahedex** [comment]
You can reach out to me at shahed739@gmail.com 
Thanks! :smiley:
